yt-dlp instead

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,35 +1,36 @@
 #! /usr/bin/env bash
-echo "-----> Installing youtube-dl"
+echo "-----> Installing yt-dlp"
 
 #change to the BUILD_DIR
 
 BUILD_DIR=${1:-}
 VENDOR_DIR="vendor"
-YTDL_NAME="youtube-dl"
+YTDL_NAME="yt-dpl"
 
 cd $BUILD_DIR
 mkdir -p $VENDOR_DIR
 cd $VENDOR_DIR
-mkdir -p youtube-dl
-cd youtube-dl
+mkdir -p yt-dlp
+cd yt-dlp
 
 
 # download the youtube-dl
-code=$(curl https://yt-dl.org/downloads/latest/youtube-dl -L --silent --fail --retry 5 --retry-max-time 15 -o ./$YTDL_NAME --write-out "%{http_code}")
+code=$(curl https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -L --silent --fail --retry 5 --retry-max-time 15 -o ./$YTDL_NAME --write-out "%{http_code}")
 
 
 if [ "$code" != "200" ]; then
-  echo "Unable to download youtubedl: $code" | output && exit 1
+  echo "Unable to download yt-dlp: $code" | output && exit 1
 fi
 
 
-chmod a+rx ./youtube-dl
+chmod a+rx ./yt-dlp
 
 # export PATH=$PATH:/$HOME/$VENDOR_DIR/youtube-dl
 # # echo $PROFILE_PATH
 
 
+
 echo $PATH
-# PROFILE_PATH="$BUILD_DIR/.profile.d/youtube-dl"
-# mkdir -p $(dirname $PROFILE_PATH)
-# echo 'export PATH="$PATH:${HOME}/vendor/youtube-dl"' >> $PROFILE_PATH
+PROFILE_PATH="$BUILD_DIR/.profile.d/yt-dlp"
+mkdir -p $(dirname $PROFILE_PATH)
+echo 'export PATH="$PATH:${HOME}/vendor/yt-dlp"' >> $PROFILE_PATH
